[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "graders-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
reqwest = { version = "0.11.12", features = ["stream"] }
serde = "1.0.145"
serde_derive = "1.0.145"
thiserror = "1.0.37"
tokio = { version = "1.24.2", features = ["fs", "io-util"] }
zip = "0.6.3"
