[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "graders-utils"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
rust-version = "1.81.0"

[dependencies]
log = "0.4.22"
reqwest = { version = "0.11.27", features = ["stream"] }
serde = "1.0.210"
serde_derive = "1.0.210"
thiserror = "1.0.64"
tokio = { version = "1.40.0", features = ["fs", "io-util"] }
zip = "2.2.0"
