[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "graders-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
failure = "0.1.6"
futures = "0.3"
lapin = {version = "0.31.0", features = ["futures"]}
lazy_static = "1.3.0"
log = "0.4.6"
reqwest = {version = "0.10.0", features = ["stream"]}
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"
tokio = { version = "0.2.9", features = ["fs", "io-util"]}
zip = "0.5.2"
