[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "graders-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
failure = "0.1.6"
log = "0.4.6"
reqwest = {version = "0.11", features = ["stream"]}
serde = "1.0.103"
serde_derive = "1.0.103"
tokio = { version = "1.0", features = ["fs", "io-util"]}
zip = "0.6.0"
