[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "graders-utils"
version = "0.1.0"

[dependencies]
futures = "0.1"
lapin-futures = "0.10.0"
lazy_static = "1.0"
log = "0.4.1"
reqwest = "0.8.4"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
tokio = "0.1"
zip = "0.3"
