[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "graders-utils"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
rust-version = "1.70.0"

[dependencies]
log = "0.4.20"
reqwest = { version = "0.11.23", features = ["stream"] }
serde = "1.0.196"
serde_derive = "1.0.196"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["fs", "io-util"] }
zip = "0.6.6"
