[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "graders-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
failure = "0.1.6"
futures = "0.1.26"
lapin-futures = "0.18.0"
lazy_static = "1.3.0"
log = "0.4.6"
reqwest = "0.9.22"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"
tokio = "0.1.18"
zip = "0.5.2"
