[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "graders-utils"
version = "0.1.0"
edition = "2018"

[dependencies]
failure = "0.1.8"
log = "0.4.17"
reqwest = { version = "0.11.12", features = ["stream"] }
serde = "1.0.145"
serde_derive = "1.0.145"
tokio = { version = "1.21.2", features = ["fs", "io-util"] }
zip = "0.6.3"
