image: rust

.test_template: &cargo_test
  stage: test
  script:
    - rustup install $RUST
    - cd xqueue-to-amqp
    - cargo +$RUST test
  cache:
    key: "$CI_BUILD_NAME"
    paths:
      - /usr/local/rustup


stable:
  <<: *cargo_test
  variables:
    RUST: stable

beta:
  <<: *cargo_test
  variables:
    RUST: beta

nightly:
  <<: *cargo_test
  variables:
    RUST: nightly
  allow_failure: true
