[package]
name = "amqp-utils"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2018"

[dependencies]
futures = "0.3.24"
lapin = "2.1.1"
log = "0.4.17"
serde = "1.0.144"
serde_derive = "1.0.144"
serde_json = "1.0.85"
thiserror = "1.0.35"
