[package]
name = "amqp-utils"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
edition = "2021"
license = "GPL-3.0"
rust-version = "1.70.0"

[dependencies]
futures = "0.3.28"
lapin = "2.3.1"
log = "0.4.20"
serde = "1.0.188"
serde_derive = "1.0.188"
serde_json = "1.0.107"
thiserror = "1.0.49"
