[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "amqp-to-test"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
rust-version = "1.70.0"

[dependencies]
env_logger = "0.10.1"
futures = "0.3.29"
log = "0.4.20"
serde = "1.0.193"
serde_derive = "1.0.193"
serde_yaml = "0.9.27"
thiserror = "1.0.50"
eyre = "0.6.9"
color-eyre = "0.6.2"

[dependencies.clap]
features = ["cargo"]
version = "4.4.8"

[dependencies.amqp-utils]
path = "../amqp-utils"

[dependencies.tokio]
features = ["macros", "rt-multi-thread", "sync"]
version = "1.34.0"
