[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "amqp-to-test"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.9.1"
futures = "0.3.24"
log = "0.4.17"
serde = "1.0.145"
serde_derive = "1.0.145"
serde_yaml = "0.9.13"
failure = "0.1.8"
failure_derive = "0.1.8"

[dependencies.clap]
features = ["cargo"]
version = "4.0.15"

[dependencies.amqp-utils]
path = "../amqp-utils"

[dependencies.tokio]
features = ["macros", "rt-multi-thread", "sync"]
version = "1.21.2"
