[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "amqp-to-test"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.9.0"
futures = "0.3"
log = "0.4.6"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_yaml = "0.8.11"
failure = "0.1.6"
failure_derive = "0.1.6"

[dependencies.clap]
features = ["yaml"]
version = "2.33.0"

[dependencies.amqp-utils]
path = "../amqp-utils"

[dependencies.graders-utils]
path = "../graders-utils"

[dependencies.tokio]
features = ["macros", "rt-multi-thread", "sync"]
version = "1.0"
