[package]
name = "amqp-to-test"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]

[dependencies]
error-chain = "0.11.0"
futures = "0.1.18"
tokio = "0.1.1"
tokio-process = "0.1.5"
lapin-futures = "0.10.0"
toml = "0.4.5"
serde = "1.0.27"
serde_derive = "1.0.27"
clap = {version = "2.30", features = ["yaml"]}
graders-utils = { path = "../graders-utils" }
log = "0.4.1"
env_logger = "0.5.3"
serde_json = "1.0.9"
