[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "amqp-to-test"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.7.1"
futures = "0.3"
lapin = {version = "0.29.1", features = ["futures"]}
log = "0.4.6"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"
serde_yaml = "0.8.11"
failure = "0.1.6"
failure_derive = "0.1.6"

[dependencies.clap]
features = ["yaml"]
version = "2.33.0"

[dependencies.graders-utils]
path = "../graders-utils"

[dependencies.tokio]
features = ["macros", "rt-threaded"]
version = "0.2.9"
