[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "amqp-to-test"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10.0"
futures = "0.3.24"
log = "0.4.17"
serde = "1.0.145"
serde_derive = "1.0.145"
serde_yaml = "0.9.13"
thiserror = "1.0.37"
eyre = "0.6.8"
color-eyre = "0.6.2"

[dependencies.clap]
features = ["cargo"]
version = "4.0.15"

[dependencies.amqp-utils]
path = "../amqp-utils"

[dependencies.tokio]
features = ["macros", "rt-multi-thread", "sync"]
version = "1.23.1"
