[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "amqp-to-test"
version = "0.1.0"

[dependencies]
env_logger = "0.5.3"
error-chain = "0.12"
futures = "0.1.18"
futures-cpupool = "0.1.8"
lapin-futures = "0.13"
log = "0.4.1"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
serde_yaml = "0.8"
tokio = "0.1.1"
tokio-current-thread = "0.1"

[dependencies.clap]
features = ["yaml"]
version = "2.30"

[dependencies.graders-utils]
path = "../graders-utils"
