[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "amqp-to-test"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
rust-version = "1.70.0"

[dependencies]
env_logger = "0.10.1"
futures = "0.3.30"
log = "0.4.21"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_yaml = "0.9.33"
thiserror = "1.0.57"
eyre = "0.6.12"
color-eyre = "0.6.2"

[dependencies.clap]
features = ["cargo"]
version = "4.4.18"

[dependencies.amqp-utils]
path = "../amqp-utils"

[dependencies.tokio]
features = ["macros", "rt-multi-thread", "sync"]
version = "1.36.0"
