[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "amqp-to-test"
version = "0.1.0"

[dependencies]
env_logger = "0.6.1"
futures = "0.1.26"
futures-cpupool = "0.1.8"
lapin-futures = "0.13.0"
log = "0.4.6"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
serde_yaml = "0.8.8"
tokio = "0.1.18"
tokio-current-thread = "0.1.6"
failure = "0.1.5"
failure_derive = "0.1.5"

[dependencies.clap]
features = ["yaml"]
version = "2.33.0"

[dependencies.graders-utils]
path = "../graders-utils"
