[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "gitlab-to-amqp"
version = "0.1.0"

[dependencies]
env_logger = "0.5.3"
futures = "0.1"
futures-cpupool = "0.1"
git2 = "0.7"
hyper = "0.12"
hyper-tls = "0.3"
lapin-futures = "0.13"
log = "0.4"
mktemp = "0.3.1"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
serde_yaml = "0.8"
tokio = "0.1.1"
url = "1.7"
url_serde = "0.2.0"
zip = "0.4"
failure = "0.1.2"

[dependencies.clap]
features = ["yaml"]
version = "2.30"

[dependencies.graders-utils]
path = "../graders-utils"

[dependencies.uuid]
features = ["v4"]
version = "0.7.0"
