[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "gitlab-to-amqp"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.9.0"
futures = "0.3.24"
git2 = "0.15.0"
hyper-tls = "0.5.0"
log = "0.4.17"
mktemp = "0.4.1"
serde = "1.0.144"
serde_derive = "1.0.144"
serde_json = "1.0.85"
serde_yaml = "0.9.13"
zip = "0.6.2"
failure = "0.1.8"
pin-utils = "0.1.0"
libc = "0.2.132"

[dependencies.clap]
features = ["cargo"]
version = "4.0.10"

[dependencies.amqp-utils]
path = "../amqp-utils"

[dependencies.graders-utils]
path = "../graders-utils"

[dependencies.hyper]
features = ["server"]
version = "0.14.20"

[dependencies.uuid]
features = ["v4"]
version = "1.1.2"

[dependencies.url]
features = ["serde"]
version = "2.3.1"

[dependencies.tokio]
features = ["macros", "rt-multi-thread"]
version = "1.21.1"
