[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "gitlab-to-amqp"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
rust-version = "1.70.0"

[dependencies]
env_logger = "0.10.1"
futures = "0.3.30"
git2 = "0.18.1"
hyper-tls = "0.5.0"
log = "0.4.20"
serde = "1.0.195"
serde_derive = "1.0.195"
serde_json = "1.0.111"
serde_yaml = "0.9.30"
zip = "0.6.6"
pin-utils = "0.1.0"
libc = "0.2.152"
eyre = "0.6.11"
color-eyre = "0.6.2"
tempfile = "3.9.0"

[dev-dependencies]
# Fake one to be able to use cargo update -Zminimal-versions
openssl = "0.10.63"

[dependencies.clap]
features = ["cargo"]
version = "4.4.18"

[dependencies.amqp-utils]
path = "../amqp-utils"

[dependencies.graders-utils]
path = "../graders-utils"

[dependencies.hyper]
features = ["server"]
version = "0.14.28"

[dependencies.uuid]
features = ["v4"]
version = "1.6.1"

[dependencies.url]
features = ["serde"]
version = "2.5.0"

[dependencies.tokio]
features = ["macros", "rt-multi-thread"]
version = "1.35.1"
