[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "gitlab-to-amqp"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.10.0"
futures = "0.3.28"
git2 = "0.18.1"
hyper-tls = "0.5.0"
log = "0.4.20"
mktemp = "0.5.1"
serde = "1.0.188"
serde_derive = "1.0.188"
serde_json = "1.0.107"
serde_yaml = "0.9.25"
zip = "0.6.6"
pin-utils = "0.1.0"
libc = "0.2.149"
eyre = "0.6.8"
color-eyre = "0.6.2"

[dependencies.clap]
features = ["cargo"]
version = "4.4.6"

[dependencies.amqp-utils]
path = "../amqp-utils"

[dependencies.graders-utils]
path = "../graders-utils"

[dependencies.hyper]
features = ["server"]
version = "0.14.27"

[dependencies.uuid]
features = ["v4"]
version = "1.4.1"

[dependencies.url]
features = ["serde"]
version = "2.4.1"

[dependencies.tokio]
features = ["macros", "rt-multi-thread"]
version = "1.33.0"
