[package]
name = "gitlab-to-amqp"
version = "0.1.0"
authors = ["Samuel Tardieu <sam@rfc1149.net>"]

[dependencies]
clap = {version = "2.30", features = ["yaml"]}
env_logger = "0.5.3"
error-chain = "0.11"
futures = "0.1"
futures-cpupool = "0.1"
git2 = "0.6.11"
graders-utils = { path = "../graders-utils" }
hyper = "0.11"
lapin-futures = "0.10"
log = "0.4.1"
mktemp = "0.3.1"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
tokio = "0.1.1"
toml = "0.4.5"
url = "1.7"
url_serde = "0.2.0"
zip = "0.3"
