[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "gitlab-to-amqp"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.7.1"
git2 = "0.11.0"
hyper = "0.13"
hyper-tls = "0.4"
lapin-futures = "0.28"
log = "0.4.6"
mktemp = "0.4.0"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"
serde_yaml = "0.8.11"
zip = "0.5.2"
failure = "0.1.6"

[dependencies.clap]
features = ["yaml"]
version = "2.33.0"

[dependencies.futures]
features = ["compat"]
version = "0.3"

[dependencies.graders-utils]
path = "../graders-utils"

[dependencies.uuid]
features = ["v4"]
version = "0.8.1"

[dependencies.url]
features = ["serde"]
version = "2.1.0"

[dependencies.tokio]
features = ["macros", "rt-threaded"]
version = "0.2.9"
