[server]
ip = "0.0.0.0"
port = 80
base_url = "http://antinea.enst.fr"

[gitlab]
token = "230348294383984f"

[package]
threads = 4
zip_dir = "/some/path/to/zip/dir"

[labs]
steps = ["lab2", "lab3"]
dir = "dragon-tiger"

[amqp]
host = "antinea.enst.fr"
port = 5672
exchange = "grader"
routing_key = "lab"
queue = "jobs"

[tester]
docker_image = "rfc1149/builder"
dir_on_host = "/home/sam/Enseignement/compilation/dragon-tiger/tests/labs"
dir_in_docker = "/labs"
parallelism = 1
program = "test.py"

[tester.test_files]

[tester.test_files.lab2]
file = "lab2/lab2.yaml"

[tester.test_files.lab3]
file = "lab2/lab2.yaml"
