[server]
ip = "0.0.0.0"
port = 80
base_url = "http://antinea.enst.fr"

[gitlab]
token = "230348294383984f"

[package]
threads = 4
zip_dir = "/some/path/to/zip/dir"

[labs]
steps = ["lab2", "lab3"]
dir = "dragon-tiger"

[amqp]
host = "antinea.enst.fr"
port = 5672
exchange = "grader"
routing_key = "lab"
