[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "builder"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
rust-version = "1.70.0"

[dependencies]
env_logger = "0.10.1"
log = "0.4.20"
mktemp = "0.5.1"
serde = "1.0.193"
serde_derive = "1.0.193"
serde_yaml = "0.9.29"
structopt = "0.3.26"
is_executable = "1.0.1"
thiserror = "1.0.53"
eyre = "0.6.11"

[dependencies.graders-utils]
path = "../graders-utils"

[dependencies.tokio]
features = ["macros", "rt-multi-thread"]
version = "1.35.1"
