[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "builder"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
rust-version = "1.74.1"

[dependencies]
env_logger = "0.10.1"
log = "0.4.21"
serde = "1.0.197"
serde_derive = "1.0.197"
serde_yaml = "0.9.34"
structopt = "0.3.26"
is_executable = "1.0.1"
thiserror = "1.0.58"
eyre = "0.6.12"
tempfile = "3.10.1"

[dependencies.graders-utils]
path = "../graders-utils"

[dependencies.tokio]
features = ["macros", "rt-multi-thread"]
version = "1.37.0"
