[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "builder"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.9.0"
log = "0.4.6"
mktemp = "0.4.0"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_yaml = "0.9.4"
structopt = "0.3.5"
failure = "0.1.6"
failure_derive = "0.1.6"
is_executable = "1.0.1"

[dependencies.graders-utils]
path = "../graders-utils"

[dependencies.tokio]
features = ["macros", "rt-multi-thread"]
version = "1.0"
