[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "builder"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.9.1"
log = "0.4.17"
mktemp = "0.4.1"
serde = "1.0.145"
serde_derive = "1.0.145"
serde_yaml = "0.9.13"
structopt = "0.3.26"
failure = "0.1.8"
failure_derive = "0.1.8"
is_executable = "1.0.1"

[dependencies.graders-utils]
path = "../graders-utils"

[dependencies.tokio]
features = ["macros", "rt-multi-thread"]
version = "1.21.2"
