[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "builder"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.6.1"
log = "0.4.6"
mktemp = "0.4.0"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_yaml = "0.8.8"
structopt = "0.2.15"
failure = "0.1.5"
failure_derive = "0.1.5"

[dependencies.graders-utils]
path = "../graders-utils"
