[package]
authors = ["Samuel Tardieu <sam@rfc1149.net>"]
name = "builder"
version = "0.1.0"

[dependencies]
env_logger = "0.5.3"
error-chain = "0.11.0"
log = "0.4.1"
mktemp = "0.3.1"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_yaml = "0.7.3"
structopt = "0.2.2"

[dependencies.graders-utils]
path = "../graders-utils"
