name: Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Docker build and push
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: 'recursive'
    - name: Login to DockerHub
      uses: docker/login-action@v1.9.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      uses: docker/build-push-action@v2.5.0
      with:
        push: true
        file: ./builder.dockerfile
        tags: rfc1149/builder:latest
